-- MySQL Script generated by MySQL Workbench
-- Sat Mar 22 13:56:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rukart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rukart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rukart` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rukart` ;

-- -----------------------------------------------------
-- Table `rukart`.`tipo_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`tipo_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento` (`documento` ASC) VISIBLE,
  INDEX `id_tipo_documento` (`id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `clientes_ibfk_1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `rukart`.`tipo_documentos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(100) NOT NULL,
  `contacto_nombre` VARCHAR(100) NULL DEFAULT NULL,
  `contacto_apellido` VARCHAR(100) NULL DEFAULT NULL,
  `nit` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nit` (`nit` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`tipo_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`tipo_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento` (`documento` ASC) VISIBLE,
  INDEX `id_tipo_documento` (`id_tipo_documento` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `rukart`.`tipo_documentos` (`id`),
  CONSTRAINT `usuarios_ibfk_2`
    FOREIGN KEY (`id_rol`)
    REFERENCES `rukart`.`tipo_roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `precio_compra` DECIMAL(10,2) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `compras_ibfk_1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `rukart`.`proveedores` (`id`),
  CONSTRAINT `compras_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `rukart`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`tipo_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`tipo_categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `fecha_fabricacion` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `lote` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `id_proveedor` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `rukart`.`tipo_categorias` (`id`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `rukart`.`proveedores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `cantidad_actual` INT NOT NULL,
  `fecha_ultima_entrada` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `inventario_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `rukart`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`tipo_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`tipo_factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`tipo_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`tipo_pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rukart`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rukart`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_venta` DATE NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `descuento` DECIMAL(10,2) NULL DEFAULT '0.00',
  `pago` DECIMAL(10,2) NOT NULL,
  `id_tipo_factura` INT NOT NULL,
  `id_tipo_pago` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_tipo_pago` (`id_tipo_pago` ASC) VISIBLE,
  INDEX `id_tipo_factura` (`id_tipo_factura` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rukart`.`clientes` (`id`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `rukart`.`usuarios` (`id`),
  CONSTRAINT `ventas_ibfk_3`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `rukart`.`tipo_pagos` (`id`),
  CONSTRAINT `ventas_ibfk_4`
    FOREIGN KEY (`id_tipo_factura`)
    REFERENCES `rukart`.`tipo_factura` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
